name: Create Tar Archive

on:
  push:
    branches:
      - main  # Adjust the branch name if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create Tar Archive
        run: tar -czf archive.tar.gz .
      
      - name: Upload Tar Archive
        uses: actions/upload-artifact@v2
        with:
          name: archive
          path: archive.tar.gz
