name: pst-gti-artemis-validation
on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  pst-gti-artemis:
    runs-on: [ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Python Virtual Environment
      run: |
        python -m venv pst-gti-artemis-venv
        source pst-gti-artemis-venv/bin/activate
        python3 upload-helm-packages.py > output.tgz
        
        
